### PR TITLE
Remove code copied from SnowyLeavesPlus

### PR DESCRIPTION
**Pull request by theRookieCoder**
I noticed that the 'bedrock leaves' functionality of your mod is directly copied from my mod, [SnowyLeavesPlus](https://github.com/theRookieCoder/SnowyLeavesPlus). This is a violation of my project's MPL licence as it does not disclose the source, provide credit, or use the same licence. If you have any issues with my code, feel free to make pull requests! I recommend that you suggest my mod to be used together with your mod rather than just copying my code.

### CODE REVIEW

**Comment by mineblock11** [comment]
This code is not copied and is respecting the original license. I will not be merging this pull request.

**Comment by mineblock11** [comment]
The license was only recently switched to MPL, so you're clearly causing crap.

**Comment by theRookieCoder** [comment]
> The license was only recently switched to MPL, so you're clearly causing crap.

Well that is false

You can see [here](https://github.com/theRookieCoder/SnowyLeavesPlus/blob/master/LICENSE) that the MPL licence is part of the initial commit

**Comment by theRookieCoder** [comment]
Well it doesn't matter what you say now. I've already reported your mod to modrinth and curseforge for copyright violation. Your modrinth mod was even delisted for a bit before you took it down.

**Comment by mineblock11** [comment]
Instead I'll be writing a better snowy leaves renderer because the blockstate one causes corruption.

**Comment by theRookieCoder** [comment]
Alright go ahead then, good luck 👍

**Comment by xanderstuff** [comment]
@theRookieCoder hey just a heads up, mineblock deleted your previous comment (and does deleting your own comment not show anything?) so what you said might be out of context
image

**Pull request closed without merging**
